<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJlVEAVR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJlVEAVR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJlVEAVR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJlVEAVR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJlVEAVR\App_KernelDevDebugContainer([
    'container.build_hash' => 'JlVEAVR',
    'container.build_id' => '2f760e9c',
    'container.build_time' => 1663767117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJlVEAVR');
