<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSJ9P9Ju\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSJ9P9Ju/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSJ9P9Ju.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSJ9P9Ju\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSJ9P9Ju\App_KernelDevDebugContainer([
    'container.build_hash' => 'SJ9P9Ju',
    'container.build_id' => '5f3d3229',
    'container.build_time' => 1663766794,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSJ9P9Ju');
