<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0axDTIM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0axDTIM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0axDTIM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0axDTIM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0axDTIM\App_KernelDevDebugContainer([
    'container.build_hash' => '0axDTIM',
    'container.build_id' => 'de6f0fe3',
    'container.build_time' => 1663607056,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0axDTIM');
